language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - make travisci-install
script:
  - make travisci-test
after_success:
  - pip install python-coveralls --use-mirrors
  - coveralls
